meta:
    description: testing the configuration and simulation

logging:
    base_level: 10
    file_level: 10
    console_level: 10
    file_name: model_watts.log

graph:
    type: nx.MultiDiGraph()
    generator: nx.fast_gnp_random_graph(n=self.config['single_sim']['num_agents'],
                                        p=0.5)
    nx_edge_list_filename: edge_list_nx.gz

single_sim:
    num_agents: 10
    agents:
        init_value: 0

batch_sim:
    threshold:
        list: [1, 3, 5]
